name: PHP Composer

on: [push, pull_request]

jobs:
  static-analysis:
    name: Static Analysis
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '7.3'
          name: Setup PHP
          coverage: xdebug
          tools: php-cs-fixer, phpunit
