name: PHP Tests

on: [push]

jobs:
  phpcs:
    runs-on: ubuntu-latest
    name: Checkout { matrix.php-versions }
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 7.3
          name: Setup PHP
          coverage: xdebug
          tools: phpcs

      - name: Test validate composer
        run: composer validate

      - name: Test with phpcs
        run: composer cs-check

  unit-tests:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php-versions: ['5.6', '7.0', '7.1', '7.2', '7.3', '7.4']
    name: phpunit
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          name: Setup PHP
          coverage: xdebug
          tools: phpunit

      - name: Cache dependencies
        uses: actions/cache@v1
        with:
          path: ${{ steps.composer-cache.outputs.dir }}
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: ${{ runner.os }}-composer-


      - name: Install Composer dependencies
        run: composer install --no-suggest --prefer-dist --optimize-autoloader

      - name: Test with phpunit
        run: composer test

      - name: Upload Coverage
        uses: codecov/codecov-action@v1
        if: matrix.php-version == 7.3
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./clover.xml
          flags: unittests
